# Generated by Django 5.0.7 on 2024-08-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_remove_like_liked_at_alter_video_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='liked_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
